/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_machine;

import Database.select;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author glenn
 */
public class Deposit extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
    }
    
    int acc;
    public Deposit(int AccNum) throws ClassNotFoundException, SQLException {
        initComponents();
        acc = AccNum;
        accLabel.setText("" + acc);
        getBalance();
    }
    int oldBalance;
   
    public void getBalance() throws ClassNotFoundException, SQLException {
      
        ResultSet rss = null;
        

        String sql = "SELECT * FROM CUSTOMER WHERE CUSTOMERID = '"+acc+"'";
        rs = select.getData(sql);
        try {
            if (rss.next()) {
                oldBalance = rss.getInt(8);
                balanceDisplayLabel.setText("" + oldBalance);
            } else {
                //Joption
                //JOptionPane.showMessageDialog(this, "please enter a valid input");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OlddepositAmount = new javax.swing.JTextField();
        confirmDepositButton = new javax.swing.JButton();
        backBuuton = new javax.swing.JButton();
        balanceLabel = new javax.swing.JLabel();
        balanceDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setForeground(new java.awt.Color(102, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setText("PROMISING TIME ATM");

        jLabel2.setText("CUSTOMER NUMBER");

        accLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(accLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel1.setBackground(new java.awt.Color(51, 123, 145));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DEPOSIT");

        jLabel4.setText(" DEPOSIT AMOUNT:");

        confirmDepositButton.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        confirmDepositButton.setForeground(new java.awt.Color(153, 0, 0));
        confirmDepositButton.setText("CONFIRM");
        confirmDepositButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmDepositButtonMouseClicked(evt);
            }
        });
        confirmDepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDepositButtonActionPerformed(evt);
            }
        });

        backBuuton.setText("BACK");
        backBuuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBuutonActionPerformed(evt);
            }
        });

        balanceLabel.setText("Balance:");

        balanceDisplayLabel.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(confirmDepositButton))
                    .addComponent(backBuuton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OlddepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(balanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balanceDisplayLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(balanceDisplayLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(OlddepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(confirmDepositButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(backBuuton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmDepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDepositButtonActionPerformed
        
        String deposit = OlddepositAmount.getText().trim();
        if (deposit.isEmpty()|| deposit.equals(0)) {
            JOptionPane.showMessageDialog(this, "Please enter a Valid input");
        
        } else if (oldBalance > Integer.valueOf(OlddepositAmount.getText())) {
            JOptionPane.showMessageDialog(this, "Insufficient Balance");

        }
        else {
            try {
                java.sql.PreparedStatement pstmt;
                String Query = "UPDATE CUSTOMER SET ACCOUNTBALANCE = ? WHERE CUSTOMERID = ?";
                pstmt = CustomerDB.getConnection().prepareStatement(Query);
                pstmt.setInt(1, oldBalance+Integer.valueOf(OlddepositAmount.getText().trim()));
                pstmt.setInt(2, acc);
                
                if(pstmt.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, "Your Total Balance has been updated");
                }else{
                    JOptionPane.showMessageDialog(this, "Missing fields");
                }
                pstmt.executeUpdate();
                pstmt.close();

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
    
        }
    }
        
         public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);

            }
        });

        
    }//GEN-LAST:event_confirmDepositButtonActionPerformed

    private void backBuutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBuutonActionPerformed
        setVisible(false);
        Account_Window accWin = new Account_Window(acc);
        accWin.setVisible(true);
    }//GEN-LAST:event_backBuutonActionPerformed

    private void confirmDepositButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmDepositButtonMouseClicked
       
//        String deposit = OlddepositAmount.getText();
//        if (deposit.isEmpty()|| deposit.equals(0)) {
//            JOptionPane.showMessageDialog(this, "Please enter a Valid input");
//        
//        } else if (oldBalance > Integer.valueOf(OlddepositAmount.getText())) {
//            JOptionPane.showMessageDialog(this, "Insufficient Balance");
//
//        }
//        else {
//            try {
//                java.sql.PreparedStatement pstmt;
//                String Query = "UPDATE CUSTOMER set ACCOUNTBALANCE = ? where CUSTOMERID = ?";
//                pstmt = CustomerDB.getConnection().prepareStatement(Query);
//                pstmt.setInt(1, oldBalance+Integer.valueOf(OlddepositAmount.getText()));
//                pstmt.setInt(2, acc);
//                
//                if(pstmt.executeUpdate() == 1){
//                    JOptionPane.showMessageDialog(this, "Your Total Balance has been updated");
//                }else{
//                    JOptionPane.showMessageDialog(this, "Missing fields");
//                }
//                pstmt.executeUpdate();
//                pstmt.close();
//
//            } catch (ClassNotFoundException ex) {
//                JOptionPane.showMessageDialog(this, ex);
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(this, ex);
//            }
//
//        }
    }//GEN-LAST:event_confirmDepositButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OlddepositAmount;
    private javax.swing.JLabel accLabel;
    private javax.swing.JButton backBuuton;
    private javax.swing.JLabel balanceDisplayLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton confirmDepositButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
